### ISSUE TITLE
Call Dash without activating it

### ISSUE THREAD

**Issue by Kapeli** [cfjedimaster/Brackets-Dash#5]
Brackets-Dash calls Dash by opening a `dash://` URL. The problem is that the system forces Dash to become active when this URL is opened.

Currently, this is not an issue. However, a future update of Dash will add support for iOS remotes. While an iOS remote is connected, extensions are redirected to it directly and Dash on OS X is not shown at all. Unfortunately there's no way for me to prevent the system from activating Dash when you open the `dash://` URL.

Instead of doing this:
```
open dash://query
```

Can you do this?
```
open -g dash://query
```

The `-g` causes Dash to not get activated if it does not want to and the user experience is a lot better as the active app does not lose focus anymore.

It is safe to make this change as soon as possible (no need to wait for a Dash update), as the current version of Dash already knows to activate itself if it needs to.

**Comment by Kapeli** [comment]
@cfjedimaster Can you take a look at this when you get a chance?

**Comment by cfjedimaster** [comment]
So I'm confused - if the person isn't using remotes, doesn't this mean Dash
won't come to the foreground?

On Tue, Jul 7, 2015 at 10:12 PM, Bogdan Popescu <notifications@github.com>
wrote:

> @cfjedimaster <https://github.com/cfjedimaster> Can you take a look at
> this when you get a chance?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cfjedimaster/Brackets-Dash/issues/5#issuecomment-119407748>
> .
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by Kapeli** [comment]
Nope. Dash will activate itself if it needs to. The change just lets Dash decide whether or not it should activate.

**Comment by cfjedimaster** [comment]
Ok, seems good.

On Wed, Jul 8, 2015 at 7:23 AM, Bogdan Popescu <notifications@github.com>
wrote:

> Nope. Dash will activate itself if it needs to. The change just lets Dash
> decide whether or not it should activate.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cfjedimaster/Brackets-Dash/issues/5#issuecomment-119556599>
> .
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by Kapeli** [comment]
Thank you! :purple_heart:
